# Generated by Django 2.1.3 on 2018-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='myblog/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(default='', max_length=300),
        ),
    ]
